#testing1
steps:

# deploy based on branch
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy schemas
  entrypoint: bash
  args:
  - '-c'
  - |

    if [ "$BRANCH_NAME" == "development" ]
    then
      gsutil rsync /schemas ${_DEV_BUCKET}
    elif [ "$BRANCH_NAME" == "stage" ]
    then
      gsutil rsync /schemas ${_STAGE_BUCKET}
    elif [ "$BRANCH_NAME" == "production" ]
    then
      gsutil rsync /schemas ${_PROD_BUCKET}
    else
      echo "Invalid branch name: $BRANCH_NAME"
      exit 1
    fi


substitutions:
    _DEV_BUCKET: gs://schema-registry-dev
    _STAGE_BUCKET: gs://schema-registry-stage
    _PROD_BUCKET: gs://schema-registry-prod
